name: Test External Providers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-external-providers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"

      - name: Set Up Environment and Install Dependencies
        run: |
          uv sync
          uv pip install -e .

      - name: Start Llama Stack server in background
        run: LLAMA_STACK_LOG_FILE=server.log nohup uv run llama stack run run.yaml --image-type venv &

      - name: Wait for Llama Stack server to be ready
        run: |
          echo "Waiting for Llama Stack server..."
          for i in {1..30}; do
            resp=$(curl -s http://localhost:8321/v1/health)
            if [ "$resp" == '{"status":"OK"}' ]; then
              echo "Llama Stack server is up!"
              if grep -q -e "remote::instructlab_kft from .*providers.d/remote/post_training/instructlab_kft.yaml" server.log; then
                echo "Llama Stack server is using InstructLab KFT provider"
                exit 0
              else
                echo "Llama Stack server is not using InstructLab KFT provider"
                echo "Server logs:"
                cat server.log
                exit 1
              fi
            fi
            sleep 1
          done
          echo "Llama Stack server failed to start"
          echo "Server logs:"
          cat server.log
          exit 1

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          retention-days: 5
          path: |
            **/*.log
